version: "3"
services:
    mysql:
        container_name: mysql.hexagonal.dev
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes: 
            - ./data/init.sql:/data/application/init.sql
            - mysql_hexagonal_go:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        networks: 
            - bubble_go
networks: 
    bubble_go:
        external: true
volumes: 
    mysql_hexagonal_go: